/**
 * Material Symbols icon subset manifest — GENERATED FILE,
 * DO NOT EDIT BY HAND.
 *
 * Regenerated automatically by `build/icon-subset-plugin.ts` (dev-server
 * start / save and `pnpm build`).  Source font:
 * @fontsource-variable/material-symbols-outlined (latin full-axes woff2,
 * subsetted to the names below).
 */

/** Every icon name carried by the committed subset font. */
export const ICON_NAMES = [
  "add",
  "add_circle",
  "adjust",
  "arrow_back",
  "arrow_forward",
  "arrow_outward",
  "bar_chart",
  "block",
  "broken_image",
  "call_split",
  "cancel",
  "chevron_left",
  "chevron_right",
  "comment",
  "commit",
  "content_copy",
  "contrast",
  "dark_mode",
  "delete",
  "download",
  "error",
  "expand_less",
  "expand_more",
  "fact_check",
  "flip_camera_android",
  "format_paragraph",
  "forum",
  "group",
  "history",
  "history_edu",
  "id_card",
  "info",
  "keyboard_arrow_down",
  "language",
  "light_mode",
  "link",
  "mail",
  "menu",
  "merge",
  "more_horiz",
  "new_releases",
  "open_in_new",
  "pause",
  "play_arrow",
  "public",
  "qr_code",
  "rate_review",
  "refresh",
  "remove",
  "replay",
  "screen_rotation",
  "settings",
  "share",
  "show_chart",
  "square",
  "star",
  "sticker",
  "swap_horiz",
  "warning",
  "zoom_in",
] as const;

/** Material Symbols ligature name accepted by `MaterialSymbol`. */
export type IconName = (typeof ICON_NAMES)[number];
